### ISSUE TITLE
Is this repo open for contribution?

### ISSUE THREAD

**Issue by KanarekLife** [drehtisch/HomeworkAtHome#27]
Hi! I've found out your repo and I think that the idea for the app is excellent. However I've found no info whether you're open to contribution from others or not and therefore I would like to ask about it. (I have some experience with asp.net core but I'm able to help with almost anything except design)

**Comment by drehtisch** [comment]
Hello and welcome on our Repo. How did you find us? 

Basically we are glad about every help we can get. Currently, however, there are still many questions, especially conceptual ones, that remain unanswered. If you would like to help shape the project, we will certainly be able to welcome you. Most of the tasks still have to be defined. So we don't have any explicit tasks you could work on yet.
